#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'isBalanced' function below.
#
# The function is expected to return a STRING.
# The function accepts STRING s as parameter.
#

def isBalanced(s):
    # Write your code here
    stack=[]
    for i in s:
        if i in '({[':
            stack.append(i)
        elif i in ')}]':
            if not stack:
                return "NO"
            
            top = stack.pop()
            if (top=='(' and i!=')') or (top =='[' and i!=']') or (top=='{' and i!='}'):
                return "NO"
    if (len(stack)==0):
        return 'YES'
    else:
        return "NO"
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    t = int(input().strip())

    for t_itr in range(t):
        s = input()

        result = isBalanced(s)
        print(result)
        fptr.write(result + '\n')

    fptr.close()
