#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the 'minimumBribes' function below.
# The function accepts INTEGER_ARRAY q as parameter.

def minimumBribes(q):
    # Write your code here
     let chaotic = false
 var bribes = 0
 for (let i = 0; i < queue.length; i++) {
   if (queue[i] — (i+1) > 2) { chaotic = true }
   for (let j = 0; j < i; j++) {
     if (queue[j] > queue[i]) { bribes++ }
     }
   }
 if(chaotic === true){
   console.log(“Too chaotic”)
 } else {
   console.log(bribes)
 }
}    
        
if __name__ == '__main__':
    t = int(input().strip())

    for t_itr in range(t):
        n = int(input().strip())

        q = list(map(int, input().rstrip().split()))

        minimumBribes(q)
